<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why book one-way trip with us_ModifySea_7f48cf</name>
   <tag></tag>
   <elementGuidId>719de5f9-8f68-412c-98ef-26bfec8414a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ModifySearchHeaderstyles__ArrowDownIcon-sc-mv2c1m-12.bgEVRC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b322ca32-d841-49fc-bea2-e8fb55eef0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ModifySearchHeaderstyles__ArrowDownIcon-sc-mv2c1m-12 bgEVRC</value>
      <webElementGuid>2d4ce559-97dc-4d4f-a1c9-ceabc3db06d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Searchpagestyles__Wrapper-sc-vkmp3n-3 jOPeri&quot;]/div[@class=&quot;ModifySearchHeaderstyles__ModifyHeader-sc-mv2c1m-0 dJtqgl&quot;]/div[@class=&quot;ModifySearchHeaderstyles__TripType-sc-mv2c1m-1 QKLnj&quot;]/div[@class=&quot;ModifySearchHeaderstyles__OutStandingWarpper-sc-mv2c1m-4 jUPeDs&quot;]/div[@class=&quot;ModifySearchHeaderstyles__ArrowDownIcon-sc-mv2c1m-12 bgEVRC&quot;]</value>
      <webElementGuid>e528fc20-4ffc-4dca-ac03-0e24c2ef1d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div</value>
      <webElementGuid>2f8ee28e-1524-4e84-85d7-fa290c4857ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>740c48c3-9964-4e95-b260-a4041b929efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
