<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Indica, Wagon R</name>
   <tag></tag>
   <elementGuidId>82766f69-33a4-41b4-b836-5cfe9db0c146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.cabName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d0152de7-6193-4656-8252-8778b9d48318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cabName</value>
      <webElementGuid>528447e3-c8f8-4fdb-8829-95c41abd330c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indica, Wagon R</value>
      <webElementGuid>87ad57bd-2a33-44c7-8a21-f08576752e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Searchpagestyles__Wrapper-sc-vkmp3n-3 jOPeri&quot;]/div[@class=&quot;Searchpagestyles__PageWrapper-sc-vkmp3n-0 ifUiCC&quot;]/div[@class=&quot;Searchpagestyles__PageRight-sc-vkmp3n-2 hwPtRX&quot;]/div[@class=&quot;InfiniteLoaderstyles__InfiniteLoaderContainer-sc-r5t67n-0 VOhWN&quot;]/div[@class=&quot;Listingstyles__ListingCard-sc-1n37j07-0 kuHnZt&quot;]/div[@class=&quot;CabListingCardHeaderStyle__CardHeader-sc-1a326je-0 gkXJJj&quot;]/div[@class=&quot;CabListingCardHeaderStyle__CabDtl-sc-1a326je-2 jlFTix&quot;]/div[@class=&quot;cabDtlhHeader&quot;]/div[@class=&quot;cabDtlhHeader&quot;]/h4[@class=&quot;cabName&quot;]</value>
      <webElementGuid>697449af-ed2e-4415-b3a6-fe8ffd0b1c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div/h4</value>
      <webElementGuid>8a8fea0c-43dc-4e2a-abd9-3b62b60f724f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹ 1611'])[1]/following::h4[1]</value>
      <webElementGuid>0dd72f29-4419-4cf3-9cb6-f64358b8b4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹ 1358'])[1]/following::h4[1]</value>
      <webElementGuid>f1703002-2822-4db9-b9b2-17fd594b65e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or Similar'])[1]/preceding::h4[1]</value>
      <webElementGuid>15a28a90-959d-4854-934a-a0509358b8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HATCHBACK'])[1]/preceding::h4[1]</value>
      <webElementGuid>30bd6660-6001-43ff-ba1e-28706a3004f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indica, Wagon R']/parent::*</value>
      <webElementGuid>72f7d8a4-0690-4ff8-8025-53996a4ebffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/h4</value>
      <webElementGuid>4f741dfe-78fb-4355-b73f-da0f0a0a5fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Indica, Wagon R' or . = 'Indica, Wagon R')]</value>
      <webElementGuid>3562df0f-18fe-449a-9a94-e6361a21bde7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
