<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hotels</name>
   <tag></tag>
   <elementGuidId>52b464a3-b4a4-41d6-97c0-fbe1dca73166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/ul/li[2]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b4d7957f-2a54-4d9f-9b17-8067e8e4b702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eqUAAy gwLfom</value>
      <webElementGuid>cae9788f-caea-43ea-a5f7-2ff42c3e296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels</value>
      <webElementGuid>1bbe4c44-6a74-4635-be4f-71e6ea8a9222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-xayxd-0 fkdZEP&quot;]/div[@class=&quot;sticky-gutter&quot;]/header[@class=&quot;happy-gi-header gi-special-theme-left header-sticky&quot;]/ul[@class=&quot;happy-nav&quot;]/li[@class=&quot;. .&quot;]/a[@class=&quot;nav-link .&quot;]/p[@class=&quot;sc-eqUAAy gwLfom&quot;]</value>
      <webElementGuid>051d34e5-9302-4149-a4f6-23d0f2ed80d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/ul/li[2]/a/p</value>
      <webElementGuid>1793ef1b-9fb4-4fcf-b7df-d8fac9b22d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domestic and International Flights'])[1]/preceding::p[17]</value>
      <webElementGuid>97f56012-5419-474e-a154-21c72d310202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::p[20]</value>
      <webElementGuid>e9e2a7ea-c1ff-4eeb-8ac5-837117a17658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotels']/parent::*</value>
      <webElementGuid>bd5a74da-1bae-4fb1-bc4e-39a2144dde30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/p</value>
      <webElementGuid>0eade9a6-d9a5-4d43-a1e1-cbc4365a6314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Hotels' or . = 'Hotels')]</value>
      <webElementGuid>b77864a8-d367-4ed9-a981-0487d42dfd00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
