<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Flights</name>
   <tag></tag>
   <elementGuidId>347c69a9-3b6f-4bc2-8660-1cb7c7af975b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.sc-gtssRu.fuNtCs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/ul/li/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3b38fd56-5ab5-48f6-913d-48ad00b96bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gtssRu fuNtCs</value>
      <webElementGuid>5782e609-24f1-4676-9cdb-fee446bd2f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flights</value>
      <webElementGuid>0d09b0a8-5423-422e-b97a-2cc19290dd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky-gutter&quot;]/header[@class=&quot;happy-gi-header gi-special-theme-left header-sticky&quot;]/ul[@class=&quot;happy-nav&quot;]/li[@class=&quot;. .&quot;]/a[@class=&quot;nav-link .&quot;]/p[@class=&quot;sc-gtssRu fuNtCs&quot;]</value>
      <webElementGuid>df6bd6bc-0059-422e-b445-bf350908a316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li/a/p</value>
      <webElementGuid>e1259f5e-57f7-46b1-bf14-a265d6181bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Hotels &amp; Homestays'])[1]/preceding::p[18]</value>
      <webElementGuid>9fcecb5c-0345-4914-afe7-748f09f83cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/preceding::p[18]</value>
      <webElementGuid>5061dd4d-bc16-4139-8059-5bf50b4dae10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Flights']/parent::*</value>
      <webElementGuid>82a27bb9-735a-4dde-b2ff-94def7a3cedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d12600f7-2abf-4366-88fb-89eb7366fe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Flights' or . = 'Flights')]</value>
      <webElementGuid>c0be8a56-c7a8-4699-89de-2b10f29e1e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
