<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Today</name>
   <tag></tag>
   <elementGuidId>a52c2bfa-e016-47fc-bb61-a91e53fc437c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.makeFlex.hrtlCenter.appendTop8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div/div[4]/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>baed72f8-6f0e-4ce6-8aa8-cbc9f756f9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>makeFlex hrtlCenter appendTop8</value>
      <webElementGuid>eff74e1e-905d-4fae-84db-f4c2d03e939d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>56a0c3e8-8ae4-4fb3-a524-38225fa60c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;home_homePge__bodyWrapperOuter__TQU2_&quot;]/div[@class=&quot;home_homePge__bodyWrapper__4MUbR&quot;]/div[@class=&quot;home_homePge__srchWdgtWrp__8fZBh&quot;]/div[@class=&quot;styles_FswContainer__CFh9B&quot;]/div[@class=&quot;styles_FswFieldCont__4NK_b&quot;]/div[@class=&quot;styles_FswFieldItem__WiCpQ styles_FswFieldItemIsFullWidth__KgdCI&quot;]/div[@class=&quot;styles_rdDySlct__dEHlH&quot;]/button[@class=&quot;styles_rdDySlct__optn__0Ur06 styles_rdDySlct__optnSelected__nR3wD&quot;]/div[@class=&quot;makeFlex hrtlCenter appendTop8&quot;]</value>
      <webElementGuid>0e53c44e-ef25-42ef-8024-dd83d7c87304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div/div[4]/div/button/div</value>
      <webElementGuid>3006e9e2-0157-484d-87bf-558c9bc68f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tatkal open'])[1]/following::div[1]</value>
      <webElementGuid>211911b5-08be-4fa8-a1d0-06d2100acf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tatkal open'])[2]/preceding::div[1]</value>
      <webElementGuid>014706dc-0bc8-455f-a459-04e2ad149ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>9099ddfb-5b63-48bb-9a75-06345a2eff4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>b74a7af1-9219-4701-a601-7451af5a4c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
