<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ToEnter Destination Name</name>
   <tag></tag>
   <elementGuidId>bf361336-914a-4bff-9c2c-b155e84f6787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb6cf275-3bd8-4074-8e5e-88344c2de06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_FswFld__UzC_6 styles_fswFld__u5UWc   </value>
      <webElementGuid>c0b6c871-6cf3-4736-b7f7-840c93c1213c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToEnter Destination Name  </value>
      <webElementGuid>cbfab69e-8fff-4246-bdde-cfe6dcc1219f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;home_homePge__bodyWrapperOuter__TQU2_&quot;]/div[@class=&quot;home_homePge__bodyWrapper__4MUbR&quot;]/div[@class=&quot;home_homePge__srchWdgtWrp__8fZBh&quot;]/div[@class=&quot;styles_FswContainer__CFh9B&quot;]/div[@class=&quot;styles_FswFieldCont__4NK_b&quot;]/div[@class=&quot;styles_FswFieldItem__WiCpQ styles_FswFieldItemIsDestination__aflHN&quot;]/div[@class=&quot;styles_FswFld__UzC_6 styles_fswFld__u5UWc&quot;]</value>
      <webElementGuid>54835cf4-0264-4c95-9b62-cad4a380b7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div/div[2]/div</value>
      <webElementGuid>f2a429b8-2117-4dcb-983b-59b4cf9b7f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Trains Status'])[1]/following::div[5]</value>
      <webElementGuid>4094d654-3bf3-4c47-b291-47ae49786fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tatkal open'])[1]/preceding::div[3]</value>
      <webElementGuid>ae333ac3-1198-4c3b-af4f-6d8570230c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::div[3]</value>
      <webElementGuid>090e6ce7-b4dd-4df0-a01b-9482cf4b64da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div</value>
      <webElementGuid>4a582267-0336-4072-8794-606b3f990a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ToEnter Destination Name  ' or . = 'ToEnter Destination Name  ')]</value>
      <webElementGuid>04ab7c1d-d3be-493e-87f1-10749b4537f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
