<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Enter Source Name</name>
   <tag></tag>
   <elementGuidId>b39b181e-02b9-45f4-a046-60b6ff161765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.styles_FswFldTitle__0nABI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div/div/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>35dec010-3e19-47e8-af6a-9cf70dcf3a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_FswFldTitle__0nABI</value>
      <webElementGuid>4169f88d-9fc9-4ba6-9dfa-33ea435f2271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter Source Name</value>
      <webElementGuid>5b1b6f77-e5a6-451f-aadd-8dd6caba35e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;home_homePge__bodyWrapperOuter__TQU2_&quot;]/div[@class=&quot;home_homePge__bodyWrapper__4MUbR&quot;]/div[@class=&quot;home_homePge__srchWdgtWrp__8fZBh&quot;]/div[@class=&quot;styles_FswContainer__CFh9B&quot;]/div[@class=&quot;styles_FswFieldCont__4NK_b&quot;]/div[@class=&quot;styles_FswFieldItem__WiCpQ&quot;]/div[@class=&quot;styles_FswFld__UzC_6 styles_fswFld__u5UWc&quot;]/p[@class=&quot;styles_FswFldTitle__0nABI&quot;]</value>
      <webElementGuid>ab1b0a0e-752f-442f-ac91-c1beae1c56e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div/div/div/p[2]</value>
      <webElementGuid>a806347e-0035-4b1d-9196-f556624a4d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Trains Status'])[1]/following::p[2]</value>
      <webElementGuid>3e370550-ff18-4101-8edb-c7aaeae06913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check PNR Status'])[1]/following::p[2]</value>
      <webElementGuid>e231e3ab-9a78-4491-86d8-889ff2141b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tatkal open'])[1]/preceding::p[8]</value>
      <webElementGuid>c4fb88ce-71f6-4337-8027-b5f7e5248489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::p[8]</value>
      <webElementGuid>90e61cae-3bae-46ed-9021-990b9041915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Source Name']/parent::*</value>
      <webElementGuid>ce598b5b-40c0-452f-8939-eabaf6b09655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/p[2]</value>
      <webElementGuid>381f24de-1e49-4681-828f-f1d60f712ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Enter Source Name' or . = 'Enter Source Name')]</value>
      <webElementGuid>d12f33d2-f915-4f79-a7a4-dd2fbe6ee728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
