<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SEARCH TRAINS</name>
   <tag></tag>
   <elementGuidId>4ec1210e-01c2-4f0c-afe9-a5e4a4592105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.styles_FswSearchCta__Tf7s4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5142863e-73b8-4a3d-bd20-748ad929a38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_FswSearchCta__Tf7s4</value>
      <webElementGuid>57596f85-bd01-44ee-9176-a5304d6079f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH TRAINS</value>
      <webElementGuid>e9cb6d1e-1e4b-4eaa-be97-8fa99aa2a2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;home_homePge__bodyWrapperOuter__TQU2_&quot;]/div[@class=&quot;home_homePge__bodyWrapper__4MUbR&quot;]/div[@class=&quot;home_homePge__srchWdgtWrp__8fZBh&quot;]/div[@class=&quot;styles_FswContainer__CFh9B&quot;]/div[@class=&quot;styles_FswSearchCtaCont__Njluv&quot;]/span[@class=&quot;styles_FswSearchCta__Tf7s4&quot;]</value>
      <webElementGuid>f18a7fd6-85a4-4e50-b72a-84de8d6c00a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/div[2]/span</value>
      <webElementGuid>15f32e39-a534-45da-a5a8-ca5f57973561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day After Tomorrow'])[1]/following::span[1]</value>
      <webElementGuid>b9879a6b-8367-4497-b9a8-b0117dca92eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tatkal open'])[3]/following::span[3]</value>
      <webElementGuid>407d79e8-95ad-4dd2-aa0c-9ac5c4a279e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Cancellation Fee'])[1]/preceding::span[2]</value>
      <webElementGuid>bc3cf102-6cae-4452-a1fb-22eff25d7f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more about cancellation'])[1]/preceding::span[2]</value>
      <webElementGuid>d314420d-868c-41cd-a1c2-bb732cdab83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH TRAINS']/parent::*</value>
      <webElementGuid>879c3969-1940-4981-9e07-6bfcf5040c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>f19c4833-bba1-4509-a4c5-21806b4d0b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SEARCH TRAINS' or . = 'SEARCH TRAINS')]</value>
      <webElementGuid>685e83e2-df03-4d12-b4f6-83a97296e2bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
