<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_check-in</name>
   <tag></tag>
   <elementGuidId>23f5483b-95ef-4ab4-9d82-166767668b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-76zvg2.r-jwli3a.r-ubezar.r-1ozqkpa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/div/div/div[3]/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b655845-a9b4-44b5-ad32-73c16ae63d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-76zvg2 r-jwli3a r-ubezar r-1ozqkpa</value>
      <webElementGuid>559264a5-0a00-4ed2-89ee-7004164b9554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ea08453c-11bf-41be-bdb4-7f84356e0ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>check-in</value>
      <webElementGuid>af36755b-e278-4d48-91da-9d8df33b2a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;css-1dbjc4n r-1niwhzg r-1jgb5lz r-r0h9e2 r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-z2wwpe r-vgw6uq r-oswwj1 r-1rngwi6 r-156q2ks r-11ict49 r-8uuktl r-136ojw6&quot;]/div[@class=&quot;css-1dbjc4n r-1d09ksm r-qklmqi r-1lz4bg0 r-1phboty r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-184aecr r-1loqt21 r-18u37iz r-779j7e r-1f1sjgu r-1otgn73&quot;]/div[@class=&quot;css-76zvg2 r-jwli3a r-ubezar r-1ozqkpa&quot;]</value>
      <webElementGuid>a456587c-d43d-44e6-8b9e-80f96409475c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/div/div[3]/div/div[2]/div[2]</value>
      <webElementGuid>155e36ee-1c3a-4dfe-b5a4-ea0a619379e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::div[3]</value>
      <webElementGuid>c5800764-dfc3-4208-85b5-6912ce7d5f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signup'])[1]/following::div[10]</value>
      <webElementGuid>9df85b4b-5b11-4043-94c6-8bb62912bd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='flight status'])[1]/preceding::div[2]</value>
      <webElementGuid>102b832b-44d6-44fb-92dd-95eb4023bde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='manage booking'])[1]/preceding::div[5]</value>
      <webElementGuid>a6387da0-cad6-47b8-a5f3-33f0a8709797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='check-in']/parent::*</value>
      <webElementGuid>dac39ba6-390c-41ae-9df0-092881ec4333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div[2]/div[2]</value>
      <webElementGuid>42b3ef32-f549-4f09-bc30-96eb1b4686f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'check-in' or . = 'check-in')]</value>
      <webElementGuid>bd554b38-0c7c-4422-b912-ee7de2297eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
