<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S Hey Sudheer</name>
   <tag></tag>
   <elementGuidId>db591dbc-300d-4220-8329-116e42e60bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login__tab_wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4b686162-a0c0-4cdb-8178-b0e0495dd5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>2dff4d11-b75a-4c45-b3ce-eb06f2523066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login__tab_wrapper</value>
      <webElementGuid>d2376670-6140-476b-a042-495064fd2f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S Hey Sudheer</value>
      <webElementGuid>3c590326-4c72-4a78-9ba8-51add082f6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-xayxd-0 fkdZEP&quot;]/div[@class=&quot;sticky-gutter&quot;]/header[@class=&quot;happy-gi-header gi-special-theme-left header-sticky&quot;]/div[@class=&quot;gr-make-flex hrtl-center gr-push-right&quot;]/div[@class=&quot;login__tab gotrible&quot;]/div[@class=&quot;login__tab_wrapper&quot;]</value>
      <webElementGuid>298c55d8-70f8-450e-89bb-301d6cd7781d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/div[2]/div/div</value>
      <webElementGuid>bf416e4b-e1ca-45e9-ad8d-3413370694cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div[2]/div/div</value>
      <webElementGuid>2361e481-33f0-4007-8433-d7cd0046572b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'S Hey Sudheer' or . = 'S Hey Sudheer')]</value>
      <webElementGuid>e6b3ee80-0f43-47e8-88a6-bdfacfb860da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
