<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter 4 digit OTP sent to_verifyOtpCo_61d545</name>
   <tag></tag>
   <elementGuidId>bbce5c6c-daae-4ad6-9839-07a2d32eaf35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41d588de-5c60-4167-a1d9-845324a0c900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Please enter verification code. Digit 1</value>
      <webElementGuid>abdb008f-bac2-4297-a47a-63d0480d630a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>71cd93db-8d7a-4e81-8fd3-2057b29537e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verifyOtpCont__otpFiled </value>
      <webElementGuid>3858e5bf-b141-48dc-be9c-c8e3831b4450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d7cc15c8-6893-4483-a64c-751a1f6e46f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9c41c1c9-7fbd-4035-8d12-788963aedbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e240df9e-4781-4dd8-86b8-cdbf79e83f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-xayxd-0 fkdZEP&quot;]/div[@class=&quot;cm__modalWraper centerMode&quot;]/div[@class=&quot;cm__modal&quot;]/div[@class=&quot;cm__modalContent&quot;]/div[@class=&quot;sc-dcJsrY cjcrGc&quot;]/div[@class=&quot;sc-iGgWBj cZvDPc&quot;]/div[@class=&quot;sc-kAyceB bwDIOk&quot;]/div[1]/div[@class=&quot;sc-jEACwC KSRCh&quot;]/div[@class=&quot;verifyOtpCont__otpCont&quot;]/div[1]/input[@class=&quot;verifyOtpCont__otpFiled&quot;]</value>
      <webElementGuid>29eb721f-b73d-4745-8bc1-dbac4000a36e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='5']</value>
      <webElementGuid>9f7a1245-cbbf-464f-8ff3-32aa013a7780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>2388ee1a-9e98-47c8-ac76-8140a395f2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6d51870e-d6ea-4866-9775-8082f439b336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>1672ec01-47ac-41be-9956-0b313d29eeb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
