<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Bus</name>
   <tag></tag>
   <elementGuidId>e0baa38d-d751-4eec-a95c-a8404d203663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/ul/li[5]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f4463ea7-911a-419b-b07e-d935c7a236f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-AxirZ jTqZXU</value>
      <webElementGuid>c686ecf6-8370-49c0-9587-d887e8f29dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bus</value>
      <webElementGuid>303b686a-d88a-46dc-a3a6-c8d3f0d7480b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;happy-gi-header gi-special-theme-left header-sticky-nope&quot;]/ul[@class=&quot;happy-nav&quot;]/li[@class=&quot;. .&quot;]/a[@class=&quot;nav-link .&quot;]/p[@class=&quot;sc-AxirZ jTqZXU&quot;]</value>
      <webElementGuid>98c1d01f-59ea-4dfc-b4f4-95351104620a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li[5]/a/p</value>
      <webElementGuid>db454c04-4fcb-4ca6-89fb-396aa87b4d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Online Cab'])[1]/preceding::p[14]</value>
      <webElementGuid>b8541e06-48eb-46df-95e2-6b009515ecdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstation One-way'])[1]/preceding::p[14]</value>
      <webElementGuid>3ec716f7-f593-4ae8-abeb-faaaaec20c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bus']/parent::*</value>
      <webElementGuid>a66872e1-47b8-4fea-b438-9f6d5a9efb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/p</value>
      <webElementGuid>684700fc-d370-499c-82e6-8d8c12cc1921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Bus' or . = 'Bus')]</value>
      <webElementGuid>df52e7bb-6e67-40ee-a6da-e00cb7c16162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
