<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Popularity</name>
   <tag></tag>
   <elementGuidId>31365aca-8ba5-4585-a78f-b1b4d233c583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles_lstngRvmpd__srtdBy___Rzim.styles_lstngRvmpd__srtdBy_cls__AMekW.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[3]/div[2]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8591ed51-7c7b-44ee-9b92-daf91aae1eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_lstngRvmpd__srtdBy___Rzim styles_lstngRvmpd__srtdBy_cls__AMekW cursor-pointer</value>
      <webElementGuid>8099b9eb-5dc9-43cc-a529-caec2bb2e25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Popularity </value>
      <webElementGuid>cd868c17-afc0-49f6-930c-c278c2b4ecd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;undefined&quot;]/div[@class=&quot;drsp_lstngRvmpd__mainCnt__rO4SW&quot;]/div[@class=&quot;drsp_lstngRvmpd__secRight__lkVaC&quot;]/div[@class=&quot;drsp_lstngRvmpd__srtByWrp__oafzV&quot;]/div[1]/div[@class=&quot;makeFlex hrtlCenter&quot;]/div[@class=&quot;makeRelative&quot;]/div[@class=&quot;styles_lstngRvmpd__srtdBy___Rzim styles_lstngRvmpd__srtdBy_cls__AMekW cursor-pointer&quot;]</value>
      <webElementGuid>438ebab3-6034-4f83-8293-7fb284378bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[3]/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>66e7bcea-f50c-43a3-8324-c09020d1a2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK TO TOP'])[1]/following::div[130]</value>
      <webElementGuid>9a9be4fe-d9ac-4888-b45a-b0c88128c965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW ROUTE'])[1]/preceding::div[2]</value>
      <webElementGuid>bd0ec013-f131-4f46-993d-076ab37282e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>6b81130f-5630-4556-ac6f-815413a2274b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Popularity ' or . = 'Popularity ')]</value>
      <webElementGuid>735ee29f-bc63-4491-b4a8-08d7f458c4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
