<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Chennai Central Railway Station_appendTop16</name>
   <tag></tag>
   <elementGuidId>9c30ba7f-c360-4c02-842e-1c433193c8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.appendTop16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>312a0d74-a31e-4e95-9640-bfe1c67f093b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://gos3.ibcdn.com/Switch-1664882765.svg</value>
      <webElementGuid>fe0c3e88-d69b-4810-8429-2eafe272393e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>appendTop16</value>
      <webElementGuid>3e2dead2-dbcd-423a-bb4e-79ef65dceb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>switch_icon</value>
      <webElementGuid>04e9ea8a-9575-4991-8a78-bd4f5fdeaf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;undefined&quot;]/div[@class=&quot;drsp_lstngRvmpd__hdrWithCalWdWrp__VXVU9&quot;]/div[@class=&quot;Search_headerCmp__XGpF3&quot;]/div[@class=&quot;Search_headerCmp__main__TxKrk&quot;]/img[@class=&quot;appendTop16&quot;]</value>
      <webElementGuid>b66685bc-693c-452a-b737-7d3d121fc729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/img</value>
      <webElementGuid>afb6130b-5db3-47ea-bdd3-995dba21a266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='switch_icon']</value>
      <webElementGuid>1a6a0a88-4433-4e43-8535-fcb7ea60edac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0155a3d0-5d28-44f3-8525-2dc1451fcdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://gos3.ibcdn.com/Switch-1664882765.svg' and @alt = 'switch_icon']</value>
      <webElementGuid>9e253886-94bf-427e-9fb4-d7339b4a5198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
