<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_CC - AC Chair Car</name>
   <tag></tag>
   <elementGuidId>43865be6-32c9-4f9b-bdd2-c8bdd7991daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[3]/div/div/div/div[3]/div/div[2]/ul/li/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d77a4511-116e-47ff-a911-aebba09d2b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Filters_filterItemTxt__D_d3w false</value>
      <webElementGuid>74dec20f-3aed-4fc4-9fd0-7090527852ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CC0</value>
      <webElementGuid>ca58137f-ef1d-421b-8da4-e87f3afba7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CC - AC Chair Car</value>
      <webElementGuid>7ed01bab-6433-452d-bf98-7fd3fbbdc3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;undefined&quot;]/div[@class=&quot;drsp_lstngRvmpd__mainCnt__rO4SW&quot;]/div[@class=&quot;drsp_lstngRvmpd__secLeft__Cn2jN&quot;]/div[@class=&quot;Filters_App__Z5yQg Filters_ScrollStyle__5GeAr&quot;]/div[@class=&quot;Filters_filterContainer__5CX12&quot;]/div[@class=&quot;undefined&quot;]/div[@class=&quot;undefined&quot;]/div[@class=&quot;undefined&quot;]/ul[@class=&quot;Filters_options__VHoJ4&quot;]/li[@class=&quot;Filters_filterItem__vb1rK&quot;]/span[@class=&quot;Filters_checkmarkOuter__B1EEf&quot;]/label[@class=&quot;Filters_filterItemTxt__D_d3w false&quot;]</value>
      <webElementGuid>83afc086-237f-42aa-9e28-55c3b0529ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[3]/div/div/div/div[3]/div/div[2]/ul/li/span/label</value>
      <webElementGuid>7c20b569-f8ab-4082-bee6-fe0436e1a406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL'])[3]/following::label[1]</value>
      <webElementGuid>dee9b5dc-baca-4ff1-bb37-21a3d6f8a749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/following::label[1]</value>
      <webElementGuid>70200135-ae97-4d84-a8c7-64076afe2a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EC - Executive Chair Car'])[1]/preceding::label[1]</value>
      <webElementGuid>b296928e-2e18-45a2-9366-014913f807fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EA - Executive Anubhuti'])[1]/preceding::label[2]</value>
      <webElementGuid>1dab6f7f-c542-44ba-b748-a5daee9a8bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CC - AC Chair Car']/parent::*</value>
      <webElementGuid>d1efaad6-9f6c-415a-8cea-493497e3c10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/ul/li/span/label</value>
      <webElementGuid>a2a51037-0485-45bc-8fe6-fffe8a0fa93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'CC - AC Chair Car' or . = 'CC - AC Chair Car')]</value>
      <webElementGuid>07595874-9d17-4a38-83cb-f2f58cd0dbc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
