<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_General</name>
   <tag></tag>
   <elementGuidId>ae09c38e-c6da-478b-b82b-8de48c74dd05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[3]/div/div/div/div[2]/div/div[2]/ul/li/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>348794ee-51fc-4c19-9967-ac137b85299b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Filters_filterItemTxt__D_d3w false</value>
      <webElementGuid>c326fa79-847e-4d2d-81e3-efc2c847dc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>General0</value>
      <webElementGuid>6ce05e0a-26d8-4470-8a1c-f26fd0722405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General</value>
      <webElementGuid>0f9645f7-03b7-4d96-850a-15298898ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;undefined&quot;]/div[@class=&quot;drsp_lstngRvmpd__mainCnt__rO4SW&quot;]/div[@class=&quot;drsp_lstngRvmpd__secLeft__Cn2jN&quot;]/div[@class=&quot;Filters_App__Z5yQg Filters_ScrollStyle__5GeAr&quot;]/div[@class=&quot;Filters_filterContainer__5CX12&quot;]/div[@class=&quot;undefined&quot;]/div[@class=&quot;undefined&quot;]/div[@class=&quot;undefined&quot;]/ul[@class=&quot;Filters_options__VHoJ4&quot;]/li[@class=&quot;Filters_filterItem__vb1rK&quot;]/span[@class=&quot;Filters_checkmarkOuter__B1EEf&quot;]/label[@class=&quot;Filters_filterItemTxt__D_d3w false&quot;]</value>
      <webElementGuid>b4e6da2c-e83c-45dd-ab37-421476ecaaaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[3]/div/div/div/div[2]/div/div[2]/ul/li/span/label</value>
      <webElementGuid>315bd8bf-9bc8-4d3d-98d7-b7040764cf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL'])[2]/following::label[1]</value>
      <webElementGuid>0ec1add9-3a5e-4c5f-bfee-525f6f748354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quota'])[1]/following::label[1]</value>
      <webElementGuid>47f4fd88-c6d2-4151-b469-3e08b52f8be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tatkal'])[1]/preceding::label[1]</value>
      <webElementGuid>7a11db8f-92fc-44a7-9784-e2129adf7b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ladies'])[1]/preceding::label[2]</value>
      <webElementGuid>115c8f54-a748-498f-b775-cc5a8ffce7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='General']/parent::*</value>
      <webElementGuid>e9d82869-1000-4f8c-8e9e-7e78fb08a92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/ul/li/span/label</value>
      <webElementGuid>0482a867-2f44-479a-a7de-db084a34319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'General' or . = 'General')]</value>
      <webElementGuid>9d7664ec-47ef-48d3-8473-cd22ed052994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
