<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bangalore City Junction_header-sprite logo</name>
   <tag></tag>
   <elementGuidId>6dcf563e-35a3-4ea4-b750-1d142efec303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.header-sprite.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f45ceb4-05cf-409c-9f1b-78477ffecbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-sprite logo</value>
      <webElementGuid>73048c77-887e-49e3-af5d-d5388c9ae5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sticky-gutter&quot;]/header[@class=&quot;happy-gi-header gi-special-theme-left header-sticky&quot;]/a[@class=&quot;gi-header-logo__home&quot;]/span[@class=&quot;header-sprite logo&quot;]</value>
      <webElementGuid>a9e57868-1484-4fe7-8f47-f4a74c2e0176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/a/span</value>
      <webElementGuid>c99423a0-603e-4646-9049-2f80cf06f397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>35f9fa06-04cf-4db6-bcc3-1f1921c21d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
