<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Popularity</name>
   <tag></tag>
   <elementGuidId>7a0cb77d-34d6-4f04-9902-c118113b1193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rubikSemiBold.styles_selectedText__p0zVa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[3]/div[2]/div[2]/div/div/div/div/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f144998f-a554-4a09-9801-235d42fd2db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rubikSemiBold styles_selectedText__p0zVa</value>
      <webElementGuid>46e3824e-11cc-4882-a4ea-55b78759c674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Popularity</value>
      <webElementGuid>3fd56385-ba31-4632-ba18-b92bdf7ca24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;undefined&quot;]/div[@class=&quot;drsp_lstngRvmpd__mainCnt__rO4SW&quot;]/div[@class=&quot;drsp_lstngRvmpd__secRight__lkVaC&quot;]/div[@class=&quot;drsp_lstngRvmpd__srtByWrp__oafzV&quot;]/div[1]/div[@class=&quot;makeFlex hrtlCenter&quot;]/div[@class=&quot;makeRelative&quot;]/div[@class=&quot;styles_lstngRvmpd__srtdBy___Rzim styles_lstngRvmpd__srtdBy_cls__AMekW cursor-pointer&quot;]/p[@class=&quot;font16 rubikSemiBold&quot;]/span[@class=&quot;rubikSemiBold styles_selectedText__p0zVa&quot;]</value>
      <webElementGuid>a67f5ca7-0ba2-44fd-a46b-dc0e5f53c48b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[3]/div[2]/div[2]/div/div/div/div/p/span</value>
      <webElementGuid>e9c6f7b1-6924-48a3-881e-dc446190764d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK TO TOP'])[1]/following::span[1]</value>
      <webElementGuid>6b0c9e0c-800b-47b1-8629-bb4abc170c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW ROUTE'])[1]/preceding::span[2]</value>
      <webElementGuid>3e20bbaa-7971-4ea7-a474-310cb9187569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 6 days availability'])[1]/preceding::span[3]</value>
      <webElementGuid>ff91e81e-7d67-41c3-acb9-e0b5dd5da4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Popularity']/parent::*</value>
      <webElementGuid>2cce7689-1e32-4ba0-9732-f21c9b5ac6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/p/span</value>
      <webElementGuid>14aed348-38ae-4d97-aab0-173c9d773b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Popularity' or . = 'Popularity')]</value>
      <webElementGuid>b64f863f-c829-4de1-9bef-9ca3182beebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
