<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_autosuggest</name>
   <tag></tag>
   <elementGuidId>922d63c8-c762-449a-a1ca-e8cd79b18f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-2-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='downshift-2-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea381575-30d0-4726-9fd8-0d15e7d12a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autosuggest</value>
      <webElementGuid>05463ab9-f94a-44b1-bb18-4ee92c01add7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87267442-fd7c-4539-b4fd-9282341f2c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>5f83e935-e4de-4b20-8d70-a93275c796e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-2-label</value>
      <webElementGuid>b77679be-88dd-41a7-a137-16cf308418ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28aa4183-4e85-4533-b9a0-6285ac9df131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-2-input</value>
      <webElementGuid>372061b0-ba62-4f15-a2c5-1a05aeb7af76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Drop location</value>
      <webElementGuid>14bab42d-8c95-474d-ab51-4dff733fa0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>D</value>
      <webElementGuid>5b96ecd5-1785-454f-a473-f81bfb55923d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-2-menu</value>
      <webElementGuid>d08028e4-0dfb-4d43-879a-67c6695e06a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-2-input&quot;)</value>
      <webElementGuid>dbcfff4f-2687-4946-89b5-443c9c2cccab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downshift-2-input']</value>
      <webElementGuid>094f08a5-937f-4b1f-bc09-dd35d9c6a29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/section/section/div[3]/div/input</value>
      <webElementGuid>ad201a5b-3e66-49aa-92cb-24f1b1bda384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>41f1f1f6-b08f-4818-8406-5ede34759a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'autosuggest' and @type = 'text' and @id = 'downshift-2-input' and @placeholder = 'Enter Drop location']</value>
      <webElementGuid>d62d4e58-d557-4f27-9fc6-32ee65475d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
