<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_To_AutoSuggeststyles__SubTxt-sc-1xb3zd-5 fYirnK</name>
   <tag></tag>
   <elementGuidId>9e047e0f-55f4-4fca-9943-bf0f1fc63a10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.AutoSuggeststyles__SubTxt-sc-1xb3zd-5.fYirnK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='downshift-2-item-0']/li/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a5fee420-e9ad-4d03-9986-6b9c3372e5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AutoSuggeststyles__SubTxt-sc-1xb3zd-5 fYirnK</value>
      <webElementGuid>58f799d9-4241-46ec-9405-d95535abc41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-2-item-0&quot;)/li[@class=&quot;AutoSuggeststyles__ListItem-sc-1xb3zd-2 kOvBXW&quot;]/div[@class=&quot;AutoSuggeststyles__ListItemContent-sc-1xb3zd-3 bpbSMe&quot;]/p[@class=&quot;AutoSuggeststyles__SubTxt-sc-1xb3zd-5 fYirnK&quot;]</value>
      <webElementGuid>a858baf1-7eb3-4118-b6f4-bc94bb7c6ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downshift-2-item-0']/li/div/p[2]</value>
      <webElementGuid>a65b11e6-39d4-4284-8549-c0945f1f113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/p[2]</value>
      <webElementGuid>d6dd51a3-30c9-4b3b-9d9c-d3ddff70f276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
