<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Outstation Round trip_CustomRadioButto_52f97c</name>
   <tag></tag>
   <elementGuidId>f957db40-20b4-458c-b583-f5e988b096b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Airport-transfer > div.CustomRadioButtonUIstyles__RadioLabel-sc-1ffkzia-0.khEbbS > span.CustomRadioButtonUIstyles__Dot-sc-1ffkzia-2.hAzeQw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Airport-transfer']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d83103c3-31a2-4992-844e-ba22f6f73cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CustomRadioButtonUIstyles__Dot-sc-1ffkzia-2 hAzeQw</value>
      <webElementGuid>dd377389-9494-4370-992d-7ceba443f291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Airport-transfer&quot;)/div[@class=&quot;CustomRadioButtonUIstyles__RadioLabel-sc-1ffkzia-0 khEbbS&quot;]/span[@class=&quot;CustomRadioButtonUIstyles__Dot-sc-1ffkzia-2 hAzeQw&quot;]</value>
      <webElementGuid>13059f62-b857-4834-917c-4f92654723b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='Airport-transfer']/div/span</value>
      <webElementGuid>55f0a5c7-1453-488a-9fa6-81f369371291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/div/span</value>
      <webElementGuid>f2b5f9dd-4ca6-441a-91d6-8eb489877147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
