<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Cabs</name>
   <tag></tag>
   <elementGuidId>58103350-a865-413c-8f87-4db72c5c9082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/ul/li[4]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a0ca90b4-7433-4a2b-8b42-c1bdd993f013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eqUAAy gwLfom</value>
      <webElementGuid>1ac837a9-a75d-4a8a-a0b1-dc6e56954daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cabs</value>
      <webElementGuid>fce62308-0de8-458b-9517-ec170a9eca99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-xayxd-0 fkdZEP&quot;]/div[@class=&quot;sticky-gutter&quot;]/header[@class=&quot;happy-gi-header gi-special-theme-left header-sticky&quot;]/ul[@class=&quot;happy-nav&quot;]/li[@class=&quot;. .&quot;]/a[@class=&quot;nav-link .&quot;]/p[@class=&quot;sc-eqUAAy gwLfom&quot;]</value>
      <webElementGuid>25ecccd7-b629-4981-9858-f3e2f4ae16ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/ul/li[4]/a/p</value>
      <webElementGuid>e01402cb-c0b6-4d59-9f55-bf7afaf71649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domestic and International Flights'])[1]/preceding::p[15]</value>
      <webElementGuid>442263b3-f64d-41da-9d78-0e1705deb8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::p[18]</value>
      <webElementGuid>564504dc-274e-4002-a165-758cdcb7b877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cabs']/parent::*</value>
      <webElementGuid>06f2ff31-c489-45e8-8a04-a6370d40dd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/p</value>
      <webElementGuid>9424136b-c715-49e2-a30a-62514ddc473f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Cabs' or . = 'Cabs')]</value>
      <webElementGuid>4d337570-5740-4215-b400-94e0e6aa89cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
