<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>806b6329-fe80-45ed-a099-e6e9b52adf85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dwebCommonstyles__ButtonBase-sc-112ty3f-13.SearchBlockUIstyles__SearchButtonAutoSuggest-sc-fity7j-13.kwEZmw.dMpVqc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/section/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e5d9cc2-b97b-4fba-bba1-56548feff5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>searchHotelBtn</value>
      <webElementGuid>bc1a7491-3b58-4c15-9cd8-6219f6fb2499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dwebCommonstyles__ButtonBase-sc-112ty3f-13 SearchBlockUIstyles__SearchButtonAutoSuggest-sc-fity7j-13 kwEZmw dMpVqc</value>
      <webElementGuid>f518c7b2-eb75-4af6-8ee3-3d71ba5d90d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>88c4462f-f105-4efc-b3f5-15c1d5134cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dwebCommonstyles__BaseColumnWrap-sc-112ty3f-2 HomePagestyles__HomeBodyWrapperSection-sc-s8m7jv-0 fVGWFo HXpRb&quot;]/div[@class=&quot;HomePagestyles__HomeBodyWrapperContentDiv-sc-s8m7jv-1 kmNUVQ&quot;]/section[@class=&quot;HomePagestyles__SearchBlockOuterWrapper-sc-s8m7jv-5 gxpKrW&quot;]/div[@class=&quot;SearchBlockUIstyles__AutoSuggestOuterWrap-sc-fity7j-0 ecbwUo&quot;]/div[@class=&quot;SearchBlockUIstyles__AutoSuggestInnerWrap-sc-fity7j-1 emHEpq&quot;]/button[@class=&quot;dwebCommonstyles__ButtonBase-sc-112ty3f-13 SearchBlockUIstyles__SearchButtonAutoSuggest-sc-fity7j-13 kwEZmw dMpVqc&quot;]</value>
      <webElementGuid>86686c38-7b4b-43ca-8b74-7f1eac8e94f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/section/div/div/button</value>
      <webElementGuid>d186bc46-b554-4ca3-96ab-650df4b1a5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='goStays'])[1]/following::button[1]</value>
      <webElementGuid>ac1200bd-8c9b-4145-a620-7b36445ac568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Couples'])[1]/following::button[1]</value>
      <webElementGuid>3175dc75-70ae-4064-8be0-f284ae76a0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>af93351d-f182-4f17-a258-bdd03a99aa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>277c17b8-50e8-4219-9c9f-fb97db5ab2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>bf879800-8e73-41ff-975d-a0a31c3e3a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
