<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Book Hotels  Homestays_CountryType</name>
   <tag></tag>
   <elementGuidId>0498a084-51f8-4d3c-91ef-145cd1394bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CountryType&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CountryType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a50bd561-2588-494f-a803-772501d03b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e7abefe3-27a0-4474-91be-a594912a8b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CountryType</value>
      <webElementGuid>171f19aa-78c1-4a17-a9bf-a2f6eff9a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SearchBlockUIstyles__RadioButton-sc-fity7j-7 bnBFyA</value>
      <webElementGuid>8a5612bf-31b0-4d4f-8514-1bcf4a7a91d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dwebCommonstyles__BaseColumnWrap-sc-112ty3f-2 HomePagestyles__HomeBodyWrapperSection-sc-s8m7jv-0 fVGWFo HXpRb&quot;]/div[@class=&quot;HomePagestyles__HomeBodyWrapperContentDiv-sc-s8m7jv-1 kmNUVQ&quot;]/section[@class=&quot;HomePagestyles__SearchBlockOuterWrapper-sc-s8m7jv-5 gxpKrW&quot;]/div[@class=&quot;SearchBlockUIstyles__AutoSuggestOuterWrap-sc-fity7j-0 ecbwUo&quot;]/div[@class=&quot;SearchBlockUIstyles__AutoSuggestInnerWrap-sc-fity7j-1 emHEpq&quot;]/div[@class=&quot;SearchBlockUIstyles__HotelTypeSelectWrap-sc-fity7j-3 gFIAAn&quot;]/div[@class=&quot;SearchBlockUIstyles__RadioButtonWrap-sc-fity7j-4 eEVxPE&quot;]/input[@class=&quot;SearchBlockUIstyles__RadioButton-sc-fity7j-7 bnBFyA&quot;]</value>
      <webElementGuid>79747acc-f3b0-46d9-b797-36ab5afd8c59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CountryType']</value>
      <webElementGuid>06d4ae82-2c59-4920-9144-0fb488969aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/section/div/div/div/div/input</value>
      <webElementGuid>370d753b-5adb-486b-8421-926aa573d320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0b56b5b1-b67c-41f2-91e4-d3e2cb945995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'CountryType']</value>
      <webElementGuid>45eb6a7f-4405-47a4-a8ff-92d29b6e523c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
