<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Book Train tickets_styles_FswTripTypeI_d34499</name>
   <tag></tag>
   <elementGuidId>0d732ff0-127d-47ad-864f-33cf461ee2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/ul/li[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a1e3351-43ac-4a23-9e1a-3679cb4dd282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_FswTripTypeItemRadio__Zy5tX </value>
      <webElementGuid>6a16166a-06fc-439f-b52a-e61f3a921973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;home_homePge__bodyWrapperOuter__TQU2_&quot;]/div[@class=&quot;home_homePge__bodyWrapper__4MUbR&quot;]/div[@class=&quot;home_homePge__srchWdgtWrp__8fZBh&quot;]/div[@class=&quot;styles_FswContainer__CFh9B&quot;]/ul[@class=&quot;styles_TripTypeCont__NdHOs&quot;]/li[@class=&quot;styles_FswTripTypeItem__aPaXl&quot;]/span[@class=&quot;styles_FswTripTypeItemRadio__Zy5tX&quot;]</value>
      <webElementGuid>931c42b4-92be-4966-963b-e86d268015e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[3]/div[2]/div/ul/li[2]/span</value>
      <webElementGuid>5853c5e3-b7dd-4581-a348-78f8fc03138c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>8628d341-f190-4bc8-b4fc-60819186f3b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
