<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>84a30a49-9f14-4fea-bb07-e5c2b6ea298c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-19vq0g0-6.gvmlSY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/section[2]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>142e9f0b-e520-4d46-a784-15981051bb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-19vq0g0-6 gvmlSY</value>
      <webElementGuid>6f0cf475-64ad-498e-8bcc-a13e77ab6770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>781a8b4f-fee7-4be8-81a0-d6da287c4885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1e4no8h-0 jSiAGt&quot;]/section[@class=&quot;sc-1e4no8h-3 ljyscc&quot;]/div[@class=&quot;sc-k2lbza-0 CVUsn&quot;]/div[@class=&quot;sc-19vq0g0-0 kVKFSg&quot;]/div[@class=&quot;sc-19vq0g0-1 eSoNsW&quot;]/button[@class=&quot;sc-19vq0g0-6 gvmlSY&quot;]</value>
      <webElementGuid>0e277a6b-24ca-417f-952d-afee00951594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/section[2]/div/div/div/button</value>
      <webElementGuid>79881140-b7fa-4346-b40b-0e538bccb864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, Traveller!'])[1]/following::button[1]</value>
      <webElementGuid>89da24fb-388f-41ac-afef-ed66644c79a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::button[1]</value>
      <webElementGuid>1c6a7f9e-c04b-481a-bc3d-157be5e9e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Flight Sectors'])[1]/preceding::button[1]</value>
      <webElementGuid>c2f84474-35be-4217-aff3-437b8c3194a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kolkata to Delhi Flight |'])[1]/preceding::button[1]</value>
      <webElementGuid>b0896a50-8980-46f6-8875-87a82fb1cb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>9182444e-8679-4ae2-ab36-8bf9fe004419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>56ef7fda-3e3f-4e18-afeb-05a3ac467d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>47078bfd-e233-4ca9-99fd-a38c1c74501b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
