<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_LOGOUT</name>
   <tag></tag>
   <elementGuidId>eabee058-7392-46bb-835f-d22dd6603875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sc-11civud-2.gyfaAe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/section[2]/div[6]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9854e76d-a85f-4cc7-9997-9519e8208237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-11civud-2 gyfaAe</value>
      <webElementGuid>f40f0e9b-0a8a-4b1e-af40-9e72db081e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>492b0b66-752e-426e-a863-3a59396ab03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1e4no8h-0 jSiAGt&quot;]/section[@class=&quot;sc-1e4no8h-3 ljyscc&quot;]/div[@class=&quot;sc-1e4no8h-4 hAlxgR&quot;]/button[@class=&quot;sc-11civud-0 fzjMGi&quot;]/span[@class=&quot;sc-11civud-2 gyfaAe&quot;]</value>
      <webElementGuid>0ae2eb9c-d645-4ca3-bac7-35486cb8ad5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/section[2]/div[6]/button/span[2]</value>
      <webElementGuid>36e854db-632d-4e13-9d26-762ec1610c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan to download'])[1]/following::span[2]</value>
      <webElementGuid>cd5de94e-5467-4825-9b01-ac63837470db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download the Goibibo app and save more'])[1]/following::span[3]</value>
      <webElementGuid>d3f4d858-95b6-4ce2-b25f-c65fe28aa9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Flight Sectors'])[1]/preceding::span[1]</value>
      <webElementGuid>8c8f80ff-ed01-4cb6-9a91-79bf83d68f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kolkata to Delhi Flight |'])[1]/preceding::span[1]</value>
      <webElementGuid>40f6cab2-531b-447c-929e-b7f2c38bd165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGOUT']/parent::*</value>
      <webElementGuid>f15ee7ef-9b18-4242-aab6-161249592eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>f4a612b2-fe0a-40b0-8a1d-6311c02cd8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>e7804305-c222-49cf-a07d-21c33273b75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
