<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_autosuggest</name>
   <tag></tag>
   <elementGuidId>8adf97df-a8ac-46ea-906a-04174920129b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#downshift-1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='downshift-1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dae0a3da-ae97-4fe4-8f00-af906496a74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autosuggest</value>
      <webElementGuid>4c10ef33-a7b7-4139-8c7e-dc1050c1e37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>022fa31f-8bd0-4edf-99b4-cf5ccf733a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>ca8d8a46-2d2c-465e-a3ef-04e3a6510b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-1-label</value>
      <webElementGuid>6bd45798-74b1-4867-8919-448406143380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fca9d983-a45a-4d89-9e18-7db5415f7e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>downshift-1-input</value>
      <webElementGuid>63d6b275-fa48-4fd2-adb4-3cb51b3d7da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Pickup location</value>
      <webElementGuid>b6fe87a7-3f11-4a8a-ac93-594b12c6a784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>284819e1-d40e-48d4-9199-1c35fc5a2169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-1-menu</value>
      <webElementGuid>82ede2a6-fbed-4d36-b359-39918d75ca8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;downshift-1-input&quot;)</value>
      <webElementGuid>40a0903e-c00e-4c1b-b52a-5040a2b35e74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='downshift-1-input']</value>
      <webElementGuid>c816226e-53b5-449d-a7e7-4f96412925af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/section/section/div[2]/div/input</value>
      <webElementGuid>fd5e9ac2-5ad0-4a69-bdf4-13420286a9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>789ce4ab-3ff2-4b7e-9f1a-376ce8d99a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'autosuggest' and @type = 'text' and @id = 'downshift-1-input' and @placeholder = 'Enter Pickup location']</value>
      <webElementGuid>61466f13-0998-4f52-802c-d1cb29ca8bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
