<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TO_autosuggest</name>
   <tag></tag>
   <elementGuidId>8ceca918-d798-4fce-b0e9-833b34adfa93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autosuggestBusSRPDestHome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autosuggestBusSRPDestHome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87d4d01e-219b-4e1c-923a-59bf46d54b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d6d6314-2926-4c21-86b6-cf77b5218781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autosuggest</value>
      <webElementGuid>bcd27b7c-b431-48f7-bd8b-20501af4cf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7d00a30-ee97-4781-b679-048a605803cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>5ca35cba-8e91-448f-8651-ba2276d6d8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-2-label</value>
      <webElementGuid>746c35c0-966f-4fc3-96fb-df83f6ad7ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a29e5c26-2652-4a1c-a69a-f58da8008794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autosuggestBusSRPDestHome</value>
      <webElementGuid>596e2e69-cf1f-4a01-ba2b-dc29dd5f2a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Destination</value>
      <webElementGuid>2c213c4b-1a08-494a-ab95-ec0fc6711bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autosuggestBusSRPDestHome&quot;)</value>
      <webElementGuid>6021c798-d475-4dc1-b194-f5fd3d98d3b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autosuggestBusSRPDestHome']</value>
      <webElementGuid>ce53a035-6caf-4e1a-b9d8-04df82d948fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/section/section/div[2]/div/input</value>
      <webElementGuid>2dfe88d8-d525-487a-8043-afd813f1a81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a34e8638-0501-4f2c-8fe5-00d2a267a4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'autosuggest' and @id = 'autosuggestBusSRPDestHome' and @placeholder = 'Enter Destination']</value>
      <webElementGuid>140fcb81-bfac-4863-bbb8-1fab5078a39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
