<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FROM_autosuggestBusSRPSrcHomeName</name>
   <tag></tag>
   <elementGuidId>027d868a-d7e4-417a-946a-bef36a1a3cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autosuggestBusSRPSrcHome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autosuggestBusSRPSrcHome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbdc90c9-c0be-4d71-84a3-2c294e817649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b1d36ad-04ec-4133-b0f2-56302412b3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05b35480-b224-4b95-9a76-2a35ea642ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autosuggestBusSRPSrcHomeName</value>
      <webElementGuid>6c194dd6-c978-421a-a6ad-8febb19bd422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>eb9aa93e-97e1-4135-84ef-728125b1cdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>downshift-1-label</value>
      <webElementGuid>6b531cde-0b77-433a-aa39-b692b28ee6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>39690447-10ca-45cb-bc1e-fbb208acf479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autosuggestBusSRPSrcHome</value>
      <webElementGuid>62332352-ae48-4eb2-a61a-c81fcf05e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Source</value>
      <webElementGuid>50140819-532b-46a6-845d-627dba80891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>42149755-d82c-472a-8b10-6c1138cf9948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>downshift-1-menu</value>
      <webElementGuid>ee20a4c1-a6fd-4089-bf5d-7f8c87129ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autosuggestBusSRPSrcHome&quot;)</value>
      <webElementGuid>fe8d3bfa-249e-49d5-b4fe-e409a1d7ee48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autosuggestBusSRPSrcHome']</value>
      <webElementGuid>14018f63-8463-457f-bc23-5c263e545f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/section/section/div/div/input</value>
      <webElementGuid>25c226c5-8ef2-49ce-826b-72f98edd38ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>21196834-405a-47e5-badb-f80182d1a79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'autosuggestBusSRPSrcHomeName' and @id = 'autosuggestBusSRPSrcHome' and @placeholder = 'Enter Source']</value>
      <webElementGuid>20ba574d-29da-445c-97ef-9ac8ebca3034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
