<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Top Rated</name>
   <tag></tag>
   <elementGuidId>06afda5a-c199-4e5b-ba41-690a7b876c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='srpCardLayoutinner']/div/div/div/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>47690b94-1ccf-4a8c-83c5-ca6fa4a00058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>488e481e-72c8-44cc-91c8-0f7b5c9aa3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Top Rated</value>
      <webElementGuid>b8de978a-c246-4d6e-98b7-6112aeffa8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;srpCardLayoutinner&quot;)/div[@class=&quot;TopFilterCards__Container-sc-18wgxt7-0 eiNZvz&quot;]/div[@class=&quot;SliderFilter__SliderWrapper-sc-th8sb5-0 inRRQT&quot;]/div[@class=&quot;SliderFilter__SliderCard-sc-th8sb5-1 jTeEsI&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;tabItem&quot;]/div[@class=&quot;cardWrapper&quot;]/p[@class=&quot;heading&quot;]</value>
      <webElementGuid>408d4076-c0f3-423d-bce9-e341f8763840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpCardLayoutinner']/div/div/div/div/div[2]/div/p</value>
      <webElementGuid>ae800748-7062-4caa-81e7-845087bdaeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Show all Amenities'])[1]/following::p[3]</value>
      <webElementGuid>3a48c15d-ef18-43f3-a819-d6b32bb85912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blankets'])[1]/following::p[3]</value>
      <webElementGuid>26d59867-fa2d-4d54-a6ab-985bc84e10b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing'])[1]/preceding::p[4]</value>
      <webElementGuid>8aae9764-e106-41db-adcb-cdc5d64b9199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/preceding::p[4]</value>
      <webElementGuid>64f6964c-97dc-4636-aa46-ff361f3a8346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Top Rated']/parent::*</value>
      <webElementGuid>df4e9bc7-6584-4741-8531-ede935583984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>c542e059-aaea-4723-b417-36737129ecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Top Rated' or . = 'Top Rated')]</value>
      <webElementGuid>779af4d4-9e07-43d8-b17f-2dc4314b62b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
