<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reset_Checkboxstyles__Checkmark-sc-17a_c60bda</name>
   <tag></tag>
   <elementGuidId>e6f6c0f4-70a5-4789-8a13-8b6cd1da362d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.Checkboxstyles__Checkmark-sc-17an8c7-1.cXxQSq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='srpCardLayout']/section/div/div/div/div/div[2]/div[2]/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8477038e-0c24-4dbb-b660-b1ca5246dfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Checkboxstyles__Checkmark-sc-17an8c7-1 cXxQSq</value>
      <webElementGuid>bd8c9c93-cfb2-48b8-a88e-fb925636b119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;srpCardLayout&quot;)/section[@class=&quot;StoriesTestPagestyles__SearchBlockOuterWrapper-sc-11w9nsp-6 eLJizy&quot;]/div[@class=&quot;SrpMainBlockstyles__SrpcardLayoutDiv-sc-1jttj24-0 jwnhYD&quot;]/div[@class=&quot;SrpMainBlockstyles__SrpcardInnerLayoutDiv-sc-1jttj24-1 bolzYx&quot;]/div[@class=&quot;SrpLeftBlockstyles__SrpLeftBlockLayoutDiv-sc-yyrxg2-0 cyIFzW&quot;]/div[@class=&quot;FiltersBlockstyles__FiltersBlockLayoutDiv-sc-v6hq3g-2 fzifhO&quot;]/div[@class=&quot;FiltersBlockstyles__PopularBlockMainDiv-sc-v6hq3g-6 jfgoXB&quot;]/div[@class=&quot;FiltersBlockstyles__NewFiltersMainDiv-sc-v6hq3g-9 dZsEaZ&quot;]/div[@class=&quot;FiltersBlockstyles__FilterOuterWrapperDiv-sc-v6hq3g-17 jyLGrD&quot;]/div[@class=&quot;FiltersBlockstyles__CheckButtonWrap-sc-v6hq3g-13 gZyCIS&quot;]/label[@class=&quot;Checkboxstyles__CheckBoxLabel-sc-17an8c7-0 cOVZOW&quot;]/span[@class=&quot;Checkboxstyles__Checkmark-sc-17an8c7-1 cXxQSq&quot;]</value>
      <webElementGuid>084710c6-c0af-45d0-a2d6-d444281c8f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='srpCardLayout']/section/div/div/div/div/div[2]/div[2]/div/div/label/span</value>
      <webElementGuid>7b5b565b-ddb5-48da-ad43-590b421dd59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>7adbb44c-1b86-44ca-9e7c-400192653dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
